import type { Metadata } from "next";
import "./globals.css";
// import "pretendard/dist/web/static/pretendard.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
        <div id="global-modal"></div>
      </body>
    </html>
  );
}
